import "./globals.scss";
import { DM_Sans } from "next/font/google";
import AppHeader from "@/components/AppHeader";
import AppFooter from "@/components/AppFooter";
import Script from "next/script";

const DMSans = DM_Sans({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={DMSans.className}>
        <AppHeader />
        {children}
        <AppFooter />

        <Script
          src="//code.tidio.co/8idttcw6wqxjy9liqinkjtmhgiupkqvr.js"
          strategy="afterInteractive"
        />
      </body>
    </html>
  );
}
